package:
  name: geatpy
  version: "2.7.0"

source:
  git_url: https://github.com/geatpy-dev/geatpy.git
  git_rev: 49a1d23f36e4a3418ad7adc0e3a20247def53401

requirements:
  build:
    - numpy 1.20.3
    - cython 0.29.36
  host:
    - python
